const mongoose = require('mongoose');

const testDataSchema = new mongoose.Schema({
  userId:String,  
  question_1: Number,
  question_2: Number,
  question_3: Number,
  question_4: Number,
  question_5: Number,
  question_6: Number,
  question_7: Number,
  question_8: Number,
  question_9: Number,
  question_10: Number,
  question_11: Number,
  question_12: Number,
  question_13: Number,
  question_14: Number,
  question_15: Number,
  question_16: Number,
  question_17: Number,
  question_18: Number,
  question_19: Number,
  question_20: Number,
  question_21: Number,
  question_22: Number,
  question_23: Number,
  question_24: Number,
  question_25: Number,
  question_26: Number,
  question_27: Number,
  question_28: Number,
  question_29: Number,
  question_30: Number,
  question_31: Number,
  question_32: Number,
  question_33: Number,
  question_34: Number,
  question_35: Number,
  question_36: Number,
  question_37: Number,
  question_38: Number,
  question_39: Number,
  question_40: Number,
  question_41: Number,
  question_42: Number,
  question_43: Number,
  question_44: Number,
  question_45: Number,
  question_46: Number,
  question_47: Number,
  question_48: Number,
  question_49: Number,
  question_50: Number,
  question_51: Number,
  question_52: Number,
  question_53: Number,
  question_54: Number,
  question_55: Number,
  question_56: Number,
  question_57: Number,
  question_58: Number,
  question_59: Number,
  question_60: Number,
  totalScore:Number
});

const TestData = mongoose.model('TestData', testDataSchema);
module.exports=TestData;
